[package]
name = "crypto-crab"
version = "0.1.0"
edition = "2018"

[dependencies]
rust_decimal = { version = "1.15", features = ["maths"] }
num-traits = "0.2"
chrono = "0.4"

[dev-dependencies]
rust_decimal_macros = "1.15"